version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - ENV=local
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/.env:/backend/.env
      - ./backend/storage:/backend/storage
      - ./backend/bootstrap/cache:/backend/bootstrap/cache
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "php artisan config:cache &&
             php artisan migrate --force &&
             php artisan articles:fetch &
             php artisan serve --host=0.0.0.0 --port=8000"
    restart: unless-stopped
    networks:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mariadb:10.4.32
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news-app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app:
    driver: bridge

volumes:
  db_data:
